name: NexoEconomy
version: 1.0-SNAPSHOT
main: me.nexo.economy.NexoEconomy
api-version: '1.21'
depend: [NexoCore]

commands:
  eco:
    description: Comando principal de economía
    aliases: [bal, balance, money, gemas, mana]
  trade:
    description: Inicia un intercambio seguro con otro jugador
  bazar:
    description: Acceso al Mercado Global
    aliases: [ bazaar, mercado, ah ]
  mercadonegro:
    description: Comandos del Mercado Negro
    aliases: [ bm, blackmarket ]
