name: NexoMechanics
version: '${project.version}'
main: me.nexo.mechanics.NexoMechanics
api-version: '1.21'
author: 'TuNombre'
description: 'Mecanicas adicionales y minijuegos.'
depend: [NexoCore, NexoEconomy]
softdepend: [NexoProtections]